version: '3.3'

services:
    mysql:
        build:
                context: ./requirements/mariadb
                args:
                        - MYSQL_DATABASE=$MYSQL_DATABASE
                        - MYSQL_ROOT_PASSWORD=$MYSQ_ROOT_PASSWORD
                        - MYSQL_USER=$MYSQL_USER
                        - MYSQL_PASSWORD=$MYSQL_PASSWORD
                        - WORDPRESS_ADMIN=$WP_ADMIN
                        - WORDPRESS_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
                        - WORDPRESS_DB_USER=$WP_USER
                        - WORDPRESS_DB_PASSWORD=$WP_USER_PASSWORD
        restart: unless-stopped
        ports:
            - "3306"
        env_file: ".env"
        environment:
            - MYSQL_DATABASE=wordpress
        volumes:
            - dbdata:/var/lib/
        networks:
            - app-network
        tty: true
    wp:
        depends_on:
            - mysql
        build:
              context: ./requirements/wordpress
              args:
                    - DOMAIN_NAME=$DOMAIN_NAME
                    - WORDPRESS_DB_NAME=$WP_DATABASE
                    - WORDPRESS_ADMIN=$WP_ADMIN
                    - WORDPRESS_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
                    - WORDPRESS_DB_USER=$WP_USER
                    - WORDPRESS_DB_PASSWORD=$WP_USER_PASSWORD
                    - WORDPRESS_DB_HOST=$WP_DB_HOST
        restart: unless-stopped
        ports:
            - "9000"
        env_file: ".env"
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - app-network
    web:
        depends_on:
            - wp
        build: ./requirements/nginx
        restart: unless-stopped
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - app-network
volumes:
    dbdata:
        driver: local
        driver_opts:
            o: bind
            type: volume
            device: /home/user42/data/dbdata
    wordpress:
        driver: local
        driver_opts:
            o: bind
            type: volume
            device: /home/user42/data/wordpress

networks:
    app-network:
