version: '3.3'

services:
    mysql:
        build: ./requirements/mariadb
        restart: unless-stopped
        ports:
            - "3306"
        env_file: ".env"
        environment:
            - MYSQL_DATABASE=wordpress
        volumes:
            - dbdata:/var/lib/
        networks:
            - app-network
        tty: true
    wp:
        depends_on:
            - mysql
        build: ./requirements/wordpress
        restart: unless-stopped
        ports:
            - "9000"
        env_file: ".env"
        environment:
            - WORDPRESS_DB_HOST=db:3306
            - WORDPRESS_DB_USER=$MYSQL_USER
            - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
            - WORDPRESS_DB_NAME=wordpress
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - app-network
    web:
        depends_on:
            - wp
        build: ./requirements/nginx
        restart: unless-stopped
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - app-network
volumes:
    dbdata:
        driver: local
        driver_opts:
            o: bind
            type: volume
            device: /home/user42/data/dbdata
    wordpress:
        driver: local
        driver_opts:
            o: bind
            type: volume
            device: /home/user42/data/wordpress

networks:
    app-network:
