version: '3.3'

services:
    mariadb:
        env_file:
                - .env
        build:
                context: ./requirements/mariadb
                args:
                        - MYSQL_DATABASE=$MYSQL_DATABASE
                        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
                        - MYSQL_USER=${MYSQL_USER}
                        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                        - WP_ADMIN=${WP_ADMIN}
                        - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
                        - WP_USER=${WP_USER}
                        - WP_USER_PASSWORD=${WP_USER_PASSWORD}
        restart: unless-stopped
        container_name: mariadb
        ports:
            - "3306"
        volumes:
            - dbdata:/var/lib
        networks:
            - app-network
        tty: true
    wordpress:
        depends_on:
            - mariadb
        env_file: .env
        build:
              context: ./requirements/wordpress
              args: 
                - DOMAIN_NAME=$DOMAIN_NAME
                - MYSQL_DATABASE=$MYSQL_DATABASE
                - WP_DATABASE:${WP_DATABASE}
                - WP_ADMIN=${WP_ADMIN}
                - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
                - WP_USER=${WP_USER}
                - WP_USER_PASSWORD=${WP_USER_PASSWORD}
                - WP_DB_HOST=${WP_DB_HOST}
        restart: unless-stopped
        container_name: wordpress
        ports:
                - "9000:9000"
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - app-network
    nginx:
        depends_on:
            - wordpress
        build: ./requirements/nginx
        restart: unless-stopped
        container_name: nginx
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - app-network
volumes:
    dbdata:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $HOME/data/dbdata
    wordpress:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $HOME/data/wordpress

networks:
    app-network:

